#!/bin/bash


# API URL for pikachu
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

# output files
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"


# Make API request and save response
HTTP_STATUS=$(curl -s -o "$OUTPUT_FILE" -w "%{http_code}" "$URL")


#Check if the request was successful
if [ "$HTTP_STATUS" -eq 200 ];  then
	echo "Data successfully saved to $OUTPUT_FILE"
else
	echo "Error: Request failed with status code $HTTP_STATUS" >> "$ERROR_FILE"
	echo "Check "$ERROR_FILE" for details"
fi
