#!/bin/bash


# List of Pokemon
POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

# create folder to store data
mkdir -p pokemon_data


# Loop through eash Pokemon
for POKEMON in ${POKEMONS[@]}
do
	echo "Fetching data for $POKEMON..."

	# API URL
	URL="https://pokeapi.co/api/v2/pokemon/$POKEMON"

	# Fetch and save data
	curl -s $URL -o "pokemon_data/$POKEMON.json"


	# check if curl is successful
	if [ $? -eq 0 ]; then
		echo "Saved data to pokemon_data/$POKEMON.json ✅"
	else
		echo "Failed to fetch data for $POKEMON ❌" >> errors.txt
	fi

	#Delay to avois rate limiting
	sleep 1

done
