#!/bin/bash


DATA_DIR=pokemon_data
CSV_FILE=pokemon_report.csv


# create csv header
echo "Name,Height (m),Weight (kg)" > $CSV_FILE


# Loop through all JSON files
for file in $DATA_DIR/*.json; do
	NAME=$(jq -r '.name' $file | sed 's/\b\(.\)/\u\1/')
	HEIGHT=$(jq -r '.height' $file | awk '{printf "%.1f", $1/10}')
	WEIGHT=$(jq -r '.weight' $file | awk '{printf "%.1f", $1/10}')

	echo "$NAME,$HEIGHT,$WEIGHT" >> $CSV_FILE
done

echo "CSV Report generated at: $CSV_FILE"

cat $CSV_FILE

# calculate averages using awk
awk -F',' '
NR>1 {
	total_height += $2
	total_weight += $3
	count++
}
END {
	printf "\nAverage Height: %.2f m\n", total_height/count
	printf "Average Weight: %.2f kg\n", total_weight/count
}' $CSV_FILE
